/**
 * QuickMeet — Application Event Bus
 * Top-level events for cross-module communication (Phase 8.5).
 */

import { createEventBus } from './eventBus.js';

export const AppEvents = {
  // Session / call lifecycle
  CALL_STARTED: 'CALL_STARTED',
  CALL_ENDING: 'CALL_ENDING',
  CALL_ENDED: 'CALL_ENDED',

  // Media
  MEDIA_READY: 'MEDIA_READY',
  MEDIA_STOPPED: 'MEDIA_STOPPED',
  MEDIA_PERMISSION_DENIED: 'MEDIA_PERMISSION_DENIED',
  MEDIA_DEVICE_CHANGED: 'MEDIA_DEVICE_CHANGED',

  // Peer connection
  PEER_NEGOTIATION_STARTED: 'PEER_NEGOTIATION_STARTED',
  PEER_NEGOTIATION_COMPLETED: 'PEER_NEGOTIATION_COMPLETED',
  PEER_CONNECTED: 'PEER_CONNECTED',
  PEER_DISCONNECTED: 'PEER_DISCONNECTED',
  REMOTE_STREAM_READY: 'REMOTE_STREAM_READY',
  ICE_CONNECTED: 'ICE_CONNECTED',
  ICE_FAILED: 'ICE_FAILED',

  // Controls
  AUDIO_MUTED: 'AUDIO_MUTED',
  AUDIO_UNMUTED: 'AUDIO_UNMUTED',
  VIDEO_DISABLED: 'VIDEO_DISABLED',
  VIDEO_ENABLED: 'VIDEO_ENABLED',

  // Screen share
  SCREEN_SHARE_STARTED: 'SCREEN_SHARE_STARTED',
  SCREEN_SHARE_STOPPED: 'SCREEN_SHARE_STOPPED',
  SCREEN_SHARE_FAILED: 'SCREEN_SHARE_FAILED',

  // Network quality
  NETWORK_QUALITY_CHANGED: 'NETWORK_QUALITY_CHANGED',
  NETWORK_RECOVERED: 'NETWORK_RECOVERED',

  // Room / signaling
  ROOM_WAITING: 'ROOM_WAITING',
  ROOM_READY: 'ROOM_READY',
  USER_JOINED: 'USER_JOINED',
  USER_LEFT: 'USER_LEFT',
  SOCKET_ERROR: 'SOCKET_ERROR',
  SOCKET_DISCONNECTED: 'SOCKET_DISCONNECTED',

  // Device management (Phase 9)
  CAMERA_CHANGED: 'CAMERA_CHANGED',
  MIC_CHANGED: 'MIC_CHANGED',
  DEVICE_CONNECTED: 'DEVICE_CONNECTED',
  DEVICE_DISCONNECTED: 'DEVICE_DISCONNECTED',
  PERMISSION_CHANGED: 'PERMISSION_CHANGED',
  SETTINGS_APPLIED: 'SETTINGS_APPLIED',
  DEVICES_UPDATED: 'DEVICES_UPDATED',

  // Collaboration
  CHAT_MESSAGE_SENT: 'CHAT_MESSAGE_SENT',
  CHAT_MESSAGE_RECEIVED: 'CHAT_MESSAGE_RECEIVED',
  REACTION_SENT: 'REACTION_SENT',
  REACTION_RECEIVED: 'REACTION_RECEIVED',
  CHAT_PANEL_OPENED: 'CHAT_PANEL_OPENED',
  CHAT_PANEL_CLOSED: 'CHAT_PANEL_CLOSED',
  UNREAD_COUNT_CHANGED: 'UNREAD_COUNT_CHANGED',
};

const bus = createEventBus();

export const on = bus.on;
export const off = bus.off;
export const once = bus.once;
export const dispatch = bus.dispatch;

// TODO Phase 10: RECORDING_STARTED, TURN_DIAGNOSTICS, ADAPTIVE_BITRATE
